name: Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  matrix-build:
    strategy:
      matrix:
        go: [ "1.25", "1.26" ]
    permissions:
      contents: read
    env:
      DEFAULT_GO: "1.26"
    name: Build with go version ${{ matrix.go }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v6
        id: go
        with:
          go-version: ${{ matrix.go }}
          cache: true

      - name: golangci-lint
        if: matrix.go == env.DEFAULT_GO
        uses: golangci/golangci-lint-action@82606bf257cbaff209d206a39f5134f0cfbfd2ee # v9.2.1
        with:
          version: latest

      - name: test
        run: go test -coverprofile=coverage.out ./...

      - name: SonarCloud Scan
        if: matrix.go == env.DEFAULT_GO && env.SONAR_TOKEN != ''
        uses: SonarSource/sonarqube-scan-action@713881670b6b3676cda39549040e2d88c70d582e # v8.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Install vulncheck
        if: matrix.go == env.DEFAULT_GO
        run: go install golang.org/x/vuln/cmd/govulncheck@latest

      - name: Print vulncheck version
        if: matrix.go == env.DEFAULT_GO
        run: govulncheck -version

      - name: Run vulnerability check
        if: matrix.go == env.DEFAULT_GO
        run: govulncheck -format text -mode source -scan symbol -show verbose -test ./...


  build:
    name: Build
    runs-on: ubuntu-slim
    needs: matrix-build
    permissions:
      contents: read
    steps:
      - run: echo "Build successful"
